### ISSUE TITLE
TypeError: u.cacheAttrs is not a function

### ISSUE THREAD

**Issue by christianbundy** [dominictarr/yap#1]
```
TypeError: u.cacheAttrs is not a function
    at render (/home/christianbundy/src/yap/apis/messages/post.js:13:7)
    at /home/christianbundy/src/yap/util.js:239:16
    at apply (/home/christianbundy/src/yap/node_modules/coherence-framework/index.js:31:14)
    at render (/home/christianbundy/src/yap/apis/message.js:12:10)
    at /home/christianbundy/src/yap/util.js:239:16
    at apply (/home/christianbundy/src/yap/node_modules/coherence-framework/index.js:31:14)
    at /home/christianbundy/src/yap/apis/public.js:81:22
    at Array.map (<anonymous>)
    at /home/christianbundy/src/yap/apis/public.js:78:16
    at /home/christianbundy/src/yap/node_modules/pull-stream/sinks/reduce.js:10:5
```

**Comment by christianbundy** [comment]
Resolved by dc1d9def09f70b567ac62185fce1ccfc1094800b
